name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  front-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Store variables
        run: |
          touch .env
          echo "REACT_APP_CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "REACT_APP_CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env

      - name: Build
        env: 
          CI: false
        run: |
          yarn install
          yarn run build

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Deploy to GitHub Pages
        run: |
          yarn run deploy

